### ISSUE TITLE
Add support for zh_cn language

### ISSUE THREAD

**Issue by YuanYuanOwO** [BlvckBytes/StorageQuery#2]

**Comment by BlvckBytes** [comment]
Since first local tests of adding support for `zh_cn` seem promising, I'd like to make the following request: could you please be so kind as to provide me with proper values for [CollisionPrefixes](https://github.com/BlvckBytes/ItemPredicateParser/blob/be37f256236a0544c62a95cbe85edf070e454360/src/main/java/me/blvckbytes/item_predicate_parser/translation/CollisionPrefixes.java) and [CustomTranslations](https://github.com/BlvckBytes/ItemPredicateParser/blob/be37f256236a0544c62a95cbe85edf070e454360/src/main/java/me/blvckbytes/item_predicate_parser/translation/CustomTranslations.java)? Just orient yourself on their English counterparts; it would also be great if the custom translations don't collide with any other names (materials, effects, enchantments, ...), but if that's impossible, there are collision-prefixes after all, so it wouldn't be a big deal. Thanks for the effort in advance! :)

**Comment by BlvckBytes** [comment]
Let me provide some additional context. The translations for `negation` (not), `disjunction` (or) and `conjunction` (and) are logical operators and thereby self-explanatory, while `amount` refers to the stack-size; `deterioration` is documented [here](https://blvckbytes.github.io/docs-item-predicate-parser/expression-syntax/deterioration-predicate), and you can read up on `exact`-mode [here](https://blvckbytes.github.io/docs-item-predicate-parser/expression-syntax/exact-mode) - this should help to get a better idea of what `CustomTranslations` are referring to.

`CollisionPrefixes` are also quite straightforward, with possibly the exception of `forInstruments`, which refers to the just recently introduced [MusicInstrument](https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/MusicInstrument.html); even though it's only used for goat-horns as of now, I'd not refer to that in the translation - it may be extended in the future.

For your reference, here's the corresponding language-file, in case you want to check against collisions by searching through it [zh_cn.json](https://github.com/user-attachments/files/17248941/zh_cn.json); used keys mainly start with `enchantment.minecraft`, `item.minecraft.` or `block.minecraft.`, `effect.minecraft.` and `instrument.minecraft.`.

**Comment by YuanYuanOwO** [comment]
My brain tries to understand but fails anyway  
How do you think #3 looks?

**Comment by BlvckBytes** [comment]
Honestly, I was really surprised by how perfectly you've implemented those changes first-try - great job! I'm super happy with it.

The only question I have would be whether there's no proper translation for "Music Instrument"? If that's the case, I'm fine with accepting your PR the way it currently is, :). We just really shouldn't change it down the road - these values are intended as constants.

**Comment by YuanYuanOwO** [comment]
> Honestly, I was really surprised by how perfectly you've implemented those changes first-try - great job! I'm super happy with it.老实说，我真的很惊讶你们在第一次尝试时就如此完美地实施了这些更改 - 干得好！我对此非常满意。
> 
> The only question I have would be whether there's no proper translation for "Music Instrument"? If that's the case, I'm fine with accepting your PR the way it currently is, :). We just really shouldn't change it down the road - these values are intended as constants.我唯一的问题是“乐器”是否没有合适的翻译？如果是这样的话，我可以按照目前的方式接受你的 PR，:)。我们真的不应该在以后改变它——这些值被设计为常量。

~~Where would this value be applied? I'd like to test it.~~

**Comment by YuanYuanOwO** [comment]
> Honestly, I was really surprised by how perfectly you've implemented those changes first-try - great job! I'm super happy with it.
> 
> The only question I have would be whether there's no proper translation for "Music Instrument"? If that's the case, I'm fine with accepting your PR the way it currently is, :). We just really shouldn't change it down the road - these values are intended as constants.

Never mind, Just finished PR  
These translations may be modified by future users, as they don't look very good to me

**Comment by BlvckBytes** [comment]
I've written a few lines about collision prefixes on a [documentation page](https://blvckbytes.github.io/docs-item-predicate-parser/expression-syntax/predicate-decision). Since we're still in very early development, I think that it's okay if we need to change them before the proper release. Just later on, when predicates actually become persisted, like on Pipe-Filters, they shouldn't necessarily change anymore, as people might depend on them, and would have to update their inputs manually otherwise.

Google translator responds with spot-on english equivalents, so it looks good to me, LOL. I'll merge it and provide you with a dev-build in just a second, so you can test it out before I make an actual release. Maybe there are still oddities to fix.

**Comment by BlvckBytes** [comment]
Please give the latest release a thorough inspection and try to search materials, enchantments, potions, etc. on your local server in Chinese; feel free to report any odd behavior! :)

**Comment by YuanYuanOwO** [comment]
Seems everything is working now!
